# Generated by Django 5.0.1 on 2024-01-18 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_num', models.IntegerField(choices=[(3, 3), (4, 4), (7, 7), (8, 8), (10, 10)])),
                ('defend_num', models.IntegerField(choices=[(3, 3), (5, 5), (8, 8), (9, 9), (10, 10)])),
                ('rule', models.CharField(max_length=10, null=True, verbose_name='룰')),
                ('is_over', models.BooleanField(default=False)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack', to='cardgame.profile', verbose_name='공격자')),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defend', to='cardgame.profile', verbose_name='수비자')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cardgame.profile', verbose_name='승리자')),
            ],
        ),
    ]
