# Generated by Django 5.0.1 on 2024-01-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_num', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (8, 8), (10, 10)])),
                ('defend_num', models.IntegerField(choices=[(0, 0), (2, 2), (3, 3), (5, 5), (6, 6)], null=True)),
                ('rule', models.CharField(max_length=10, null=True, verbose_name='룰')),
                ('is_over', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
