# Generated by Django 5.0.1 on 2024-01-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='attack_num',
            field=models.IntegerField(choices=[(1, 1), (4, 4), (5, 5), (9, 9), (10, 10)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='defend_num',
            field=models.IntegerField(choices=[(0, 0), (4, 4), (5, 5), (9, 9), (10, 10)], null=True),
        ),
    ]
